### ISSUE TITLE
AttributeError: 'ClipGpt2Model' object has no attribute 'encode_image'

### ISSUE THREAD

**Issue by beyzacevik** [dhg-wei/DeCap#3]
Thanks for uploading the trained model. 

I install the clip using the following command: 
!pip install openai-clip

I receive this error when I try to run inference. 
AttributeError: 'ClipGpt2Model' object has no attribute 'encode_image'

How can I solve this?

**Comment by kirenzh** [comment]
I have the same question

**Comment by dhg-wei** [comment]
Sorry about that.
The bug has been fixed.
