### ISSUE TITLE
The metrics in the paper

### ISSUE THREAD

**Issue by TIan1874** [dhg-wei/DeCap#4]
Thanks very much for your excellent work and congratulations on your paper being accepted by ICLR 2023! I want to reproduce the work, and I am wondering if you could make public the code for calculating the metrics in the paper, such as BLEU@4, METEOR, CIDEr, and SPICE. I would appreciate it if you could take the time to reply to me.

**Comment by dhg-wei** [comment]
The captioning evaluation tool can be found [here](https://github.com/tylin/coco-caption).
