### ISSUE TITLE
Can you share the feature visualization code in Appendix G?

### ISSUE THREAD

**Issue by KN1GHT9** [dhg-wei/DeCap#8]
I use t-SNE but can't get the visualization in the paper, can you share the code for embedding feature visualization?

**Comment by KN1GHT9** [comment]
Which validation data did you choose in Figure (d) of Appendix G?

**Comment by JingyuLi-code** [comment]
Same question, can you share your t-sne code and features?

**Comment by rongtongxueya** [comment]
have same question,I'm asking good people to help me
